
services:
  backend:
    build: apps/backend/chat-service
    container_name: chat_service_backend
    ports:
      - "3092:3092"
    environment:
      ACTIVE_SPRING_PROFILES: ${ACTIVE_SPRING_PROFILES}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DEFAULT_SCHEMA: ${SPRING_DATASOURCE_DEFAULT_SCHEMA}
      SPRING_DATASOURCE_GLOBAL_SCHEMA: ${SPRING_DATASOURCE_GLOBAL_SCHEMA}
      CLOUD_AWS_ACCESS_KEY: ${CLOUD_AWS_ACCESS_KEY}
      CLOUD_AWS_SECRET_KEY: ${CLOUD_AWS_SECRET_KEY}
      PRIVATE_BUCKET_NAME: ${PRIVATE_BUCKET_NAME}
      LOG_ELK_HOST: ${LOG_ELK_HOST}
      LOG_ELK_PORT: ${LOG_ELK_PORT}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      SWAGGER_BACKEND_MAIN_JSON_URL: ${SWAGGER_BACKEND_MAIN_JSON_URL}
      HEALTH_CHECK_REDIS_SECRET_KEY: ${HEALTH_CHECK_REDIS_SECRET_KEY}
      HEALTH_CHECK_COMMIT_INFO_SECRET_KEY: ${HEALTH_CHECK_COMMIT_INFO_SECRET_KEY}
      AWS_COGNITO_USERPOOL_ID: ${AWS_COGNITO_USERPOOL_ID}
      AWS_COGNITO_REGION: ${AWS_COGNITO_REGION}
      AWS_COGNITO_JWKS_URL: ${AWS_COGNITO_JWKS_URL}
      AWS_COGNITO_CLIENT_ID: ${AWS_COGNITO_CLIENT_ID}
    networks:
      - infra_network

  frontend:
    build: apps/frontend/hushchat-mobile
    container_name: chat_service_frontend
    ports:
      - "8081:80"
    networks:
      - infra_network

networks:
  infra_network:
    external: true
    name: infra_network