databaseChangeLog:
  - changeSet:
      id: attach-existing-sequence-to-workspace-id
      author: pavithra
      tag: release-4.1
      changes:
        - addDefaultValue:
            tableName: workspace
            columnName: id
            defaultValueSequenceNext: workplace_generator

  - changeSet:
      id: sync-existing-workspace-generator-sequence
      author: pavithra
      tag: release-4.2
      changes:
        - sql:
            sql: |
              SELECT setval(
                'platform.workplace_generator',
                (SELECT COALESCE(MAX(id), 1) FROM platform.workspace)
              );
