blank_issues_enabled: true

contact_links:
  - name: "Report a security vulnerability"
    url: https://github.com/HushChat/hush-chat/blob/main/SECURITY.md
    about: "Please review our security policy and follow the instructions for responsible disclosure."
