name: "User Story"
description: "Define a new feature or functionality request from a user’s perspective."
title: "[User Story]: "
labels: ["user-story", "feature"]

body:
  - type: markdown
    attributes:
      value: |
        **User Story Template**  
        Use this form to describe a feature or enhancement from the end user’s point of view.  
        Clearly outline the goal, motivation, and expected outcome.

  - type: input
    id: title
    attributes:
      label: "Story Title"
      description: "Provide a concise and descriptive title."
      placeholder: "Example: Allow users to pin important messages in a chat"
    validations:
      required: true

  - type: textarea
    id: story
    attributes:
      label: "As a [role], I want [feature], so that [benefit]"
      description: "Write the user story in this standard format."
      placeholder: "Example: As a team member, I want to pin important messages so I can easily find key updates later."
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "List clear conditions that must be met for this story to be considered complete."
      placeholder: |
        - User can pin and unpin messages.
        - Pinned messages appear at the top of the chat.
        - Only workspace admins can remove other users’ pinned messages.
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context or Notes"
      description: "Include screenshots, mockups, or details that help the team understand the feature."
      placeholder: "Example: This feature should also be supported on the mobile app."

  - type: dropdown
    id: priority
    attributes:
      label: "Priority Level"
      description: "How important is this story for users?"
      options:
        - High
        - Medium
        - Low

  - type: checkboxes
    id: checklist
    attributes:
      label: "Before submitting"
      options:
        - label: "I confirmed that this user story doesn’t duplicate an existing one."
          required: true
        - label: "I’ve filled in all required details and acceptance criteria."
          required: true
