databaseChangeLog:
  - changeSet:
      id: create_contact_us_messages_table
      author: isali
      tag: release-7.1
      changes:
        - createTable:
            tableName: contact_us
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: email
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: subject
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: message
                  type: TEXT
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: DATETIME
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false

  - changeSet:
      id: create_contact_us_attachments_table
      author: isali
      tag: release-7.2
      changes:
        - createTable:
            tableName: contact_us_attachments
            columns:
              - column:
                  name: contact_message_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_contact_us_message_attachment
                    references: contact_us(id)
                    deleteCascade: true
              - column:
                  name: original_file_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: indexed_file_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false