databaseChangeLog:
  - changeSet:
      id: add_pinned_message_until_to_conversation
      author: ransilu
      tag: release-11.1
      comment: "add new pinned_message_until column to conversation table"
      changes:
        - addColumn:
            tableName: conversation
            columns:
              - column:
                  name: pinned_message_until
                  type: timestamptz
                  constraints:
                    nullable: true