import { HEARTBEAT_INTERVAL } from "@/hooks/ws/wsHeartbeat";

export const CONFIG = {
  INITIAL_RETRY_DELAY: 1000,
  MAX_RETRY_DELAY: 30000,
  RETRY_MULTIPLIER: 1.5,
  MAX_RECONNECT_ATTEMPTS: 50,
  CONNECTION_DEBOUNCE_DELAY: 1000,
  CONNECTION_TIMEOUT: 30000,
  HEALTH_CHECK_INTERVAL: 60000,
  STALE_CONNECTION_THRESHOLD: HEARTBEAT_INTERVAL * 3,
} as const;
