import { PLATFORM } from "@/constants/platformConstants";

const DEFAULT_MOBILE_ACTIVE_OPACITY = 0.7;
const DEFAULT_DESKTOP_ACTIVE_OPACITY = 1;

export const DEFAULT_ACTIVE_OPACITY = PLATFORM.IS_WEB
  ? DEFAULT_DESKTOP_ACTIVE_OPACITY
  : DEFAULT_MOBILE_ACTIVE_OPACITY;
export const DEFAULT_HIT_SLOP = 10;
