name: Chat Liquibase migrations

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure-dev/db-migrations/**'
  workflow_dispatch:

jobs:
  liquibase-migration-chat-db:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: Traders-Room/platform
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: main
          path: platform

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: Traders-Room/platform
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: main
          path: platform

      - name: Run workspace schemas Liquibase update
        env:
          JDBC_URL: ${{ secrets.CHAT_SPRING_DATASOURCE_URL }}
          JDBC_USERNAME: ${{ secrets.CHAT_SPRING_DATASOURCE_USERNAME }}
          JDBC_PASSWORD: ${{ secrets.CHAT_SPRING_DATASOURCE_PASSWORD }}
          CHANGELOG_FILE: 'platform/infrastructure-dev/db-migrations/workspaces/db.changelog-root.yaml'
          CLASSPATH: '/home/skynet/liquibase/postgresql-42.2.25.jar'
          SCHEMA: 'workspace'
        run: |
          liquibase \
            --driver=org.postgresql.Driver \
            --changeLogFile=$CHANGELOG_FILE \
            --classpath=$CLASSPATH \
            --url=$JDBC_URL \
            --username=$JDBC_USERNAME \
            --password=$JDBC_PASSWORD \
            --defaultSchemaName=$SCHEMA \
            --liquibaseSchemaName=$SCHEMA \
            --logLevel=debug \
            update
        shell: bash

      - name: Run platform Liquibase update
        env:
          JDBC_URL: ${{ secrets.CHAT_SPRING_DATASOURCE_URL }}
          JDBC_USERNAME: ${{ secrets.CHAT_SPRING_DATASOURCE_USERNAME }}
          JDBC_PASSWORD: ${{ secrets.CHAT_SPRING_DATASOURCE_PASSWORD }}
          CHANGELOG_FILE: 'hush-chat/infrastructure-dev/db-migrations/platform/db.changelog-root.yaml'
          CLASSPATH: '/home/skynet/liquibase/postgresql-42.2.25.jar'
          SCHEMA: 'platform'
        run: |
          liquibase \
            --driver=org.postgresql.Driver \
            --changeLogFile=$CHANGELOG_FILE \
            --classpath=$CLASSPATH \
            --url=$JDBC_URL \
            --username=$JDBC_USERNAME \
            --password=$JDBC_PASSWORD \
            --defaultSchemaName=$SCHEMA \
            --liquibaseSchemaName=$SCHEMA \
            --logLevel=debug \
            update
        shell: bash