name: Backend PR Build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'apps/backend/chat-service/**'
  push:
    paths:
      - 'apps/backend/chat-service/**'
    branches:
      - release

jobs:
  build-chat-service:
    name: Build Chat Service
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn

      - name: Build chat service
        run: |
          mvn -f apps/backend/chat-service/pom.xml clean install
          mvn -f apps/backend/chat-service/pom.xml jacoco:report